// API publique de la composition de l'espace client : sections selon les
// services, calendrier, profil d'accompagnement.

export {
  buildEvents,
  dayKey,
  monthGrid,
  upcoming,
  type CalendarEvent,
  type EventKind,
  type MonthDay,
} from "./calendar";
export { clientProfile, type ClientProfile } from "./profile";
export { chapitresDuCorps, ordreDeLecture, resume, type ChapitreCorps } from "./lecture";
export {
  actionsFor,
  actionsVerdict,
  ANTICIPATION_DAYS,
  BACKUP_MAX_AGE_DAYS,
  buildFrise,
  byPhase,
  isOpenOpportunity,
  STATUT_PROPOSITION,
  isPendingProposition,
  lastSuccessfulBackup,
  missionsOf,
  missionsVerdict,
  sitePoints,
  siteVerdict,
  withoutPrice,
  type Action,
  type ActionKind,
  type Actions,
  type Frise,
  type FriseLane,
  type FriseMark,
  type FriseTone,
  type Mission,
  type MissionKind,
  type Phase,
  type SitePoint,
  type Verdict,
} from "./pilotage";
export {
  GROUP_LABELS,
  GROUP_QUESTIONS,
  GROUP_SLUGS,
  groupFromSlug,
  SYNTHESE_SEGMENT,
  visibleGroups,
  type VisibleGroup,
  hasPersonalisedWatch,
  LEGACY_SLUGS,
  arbitrageOuvert,
  sectionByKey,
  SECTIONS,
  visibleSections,
  sectionsSansInformation,
  type Informations,
  type Contents,
  type Section,
  type SectionGroup,
  type SectionKey,
  type ServiceCode,
} from "./sections";
export {
  estColonneGravite,
  lireGravite,
  lirePhase,
  lireSeverites,
  lireSynthese,
  type Fiche,
  type Gravite,
  type Phase as PhaseAudit,
  type Point,
  type Rubrique,
  type Severites,
  type Synthese,
} from "./synthese";
export {
  DOMAINES,
  estColonneScore,
  estColonneSolution,
  estTableauScenarios,
  etatVersion,
  lireDomaine,
  lireEtiquettesPoint,
  lireNomScenario,
  lireNombre,
  lireReference,
  lireSolution,
  lireStatutScenario,
  registreEncadre,
  roleColonneScenario,
  statutScore,
  type Domaine,
  type EtatVersion,
  type EtiquettesPoint,
  type Reference,
  type Registre,
  type RoleScenario,
  type Statut,
  type StatutScenario,
} from "./lecture-audit";
export {
  ANNONCE_FIN_SUIVI_JOURS,
  MASQUAGE_JOURS,
  prochaineEtape,
  SEUIL_ARBITRAGES,
  type FaitsEspace,
  type Suggestion,
} from "./suggestions";
export { masquerSuggestion, suggestionsMasquees } from "./suggestions-store";
export { SERVICES_RECURRENTS, VEILLE_OFFERTE_MOIS, veilleOfferte, type VeilleOfferte } from "./veille-offerte";
